### PR TITLE
Update to match the latest Resume.JSON format

### PR DESCRIPTION
**Pull request by housamz**
## Changes
- Added the following keys in the `Output` object: `volunteer`, `awards`, `certificates`.
- Updated `Position` to have keys `name` and `url` instead of `company` and `website`.
- Updated `Education` to have keys `score` instead of `gpa` and added `url`.
- Fixed the empty fields in `basics.location` by splitting `geoLocation` into `city` and `country`.
- Updated the `CountryCode` search to use the `Country` key in the `geoLocation` object.
- Added Regex to extract the website and insert it in `basics.url`.
- Updated `basics.picture` to be `basics.image`.
- Updated `basics.website` to be `basics.url`.
- updated `project.summary` to be `project.description`.
- Added `endDate` and `highlights` in `project`.
- Updated `publications.website` to be `publications.url`.
- Added the following feature:
  - processAwards: Extracts the awards from the `Honors.csv` file and adds them to the `Output` object.
  - processCertificates: Extracts the certificates from the `Certifications.csv` file and adds them to the `Output` object. The certificates are sorted by date.
  - processEndorsements: Extracts the endorsements from the `Endorsement_Received_Info.csv` file and use them to insert a `level` in `skills`. The `skills` are sorted by `level`.
  - processFollows: Extracts the followers from the `Causes You Care About.csv`, `Company Follows.csv`, and `Hashtag_Follows.csv` files and use them to fill the `interests`.

### CODE REVIEW

**Comment by thomasdavis** [comment]
Really good work @housamz 

There have been quite a few issues because of the schema changes (my fault for not having a good pipeline for it)

**Comment by housamz** [comment]
@thomasdavis Thanks very much for your comment (and the JSON resume).

**Comment by JMPerez** [comment]
Thank you so much for your work, @housamz!

**Comment by housamz** [comment]
Done, thanks

**Pull request merged**
